#!/usr/bin/env bash
# Regenerates lib/supabase/database.types.ts from the migrations, using the
# same throw-away Postgres database as `npm run test:db`.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
bash "$ROOT/scripts/test-db.sh" >/dev/null
URL="postgresql://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@${PGHOST_TCP:-localhost}:${PGPORT:-5432}/${TEST_DB_NAME:-leblond_test}?sslmode=disable"
OUT="$ROOT/lib/supabase/database.types.ts"
{
  echo "// Generated by scripts/gen-db-types.sh from supabase/migrations — do not edit by hand."
  npx --yes supabase@2 gen types typescript --db-url "$URL" --schema public 2>/dev/null
} > "$OUT"
npx --yes prettier@3 --write --print-width 120 "$OUT" >/dev/null
echo "✓ wrote $OUT"
