// Generated by scripts/gen-db-types.sh from supabase/migrations — do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      ai_usage: {
        Row: {
          id: string;
          input_tokens: number | null;
          latency_ms: number | null;
          model: string;
          output_tokens: number | null;
          request_type: string;
          succeeded: boolean;
          timestamp: string;
          user_id: string;
        };
        Insert: {
          id?: string;
          input_tokens?: number | null;
          latency_ms?: number | null;
          model: string;
          output_tokens?: number | null;
          request_type: string;
          succeeded?: boolean;
          timestamp?: string;
          user_id?: string;
        };
        Update: {
          id?: string;
          input_tokens?: number | null;
          latency_ms?: number | null;
          model?: string;
          output_tokens?: number | null;
          request_type?: string;
          succeeded?: boolean;
          timestamp?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      attempts: {
        Row: {
          attempt_number: number;
          created_at: string;
          id: string;
          notes: string | null;
          perceived_difficulty: number | null;
          problem_id: string;
          result: Database["public"]["Enums"]["attempt_result"];
          session_id: string;
          started_at: string | null;
          user_id: string;
        };
        Insert: {
          attempt_number: number;
          created_at?: string;
          id?: string;
          notes?: string | null;
          perceived_difficulty?: number | null;
          problem_id: string;
          result: Database["public"]["Enums"]["attempt_result"];
          session_id: string;
          started_at?: string | null;
          user_id?: string;
        };
        Update: {
          attempt_number?: number;
          created_at?: string;
          id?: string;
          notes?: string | null;
          perceived_difficulty?: number | null;
          problem_id?: string;
          result?: Database["public"]["Enums"]["attempt_result"];
          session_id?: string;
          started_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "attempts_problem_id_fkey";
            columns: ["problem_id"];
            isOneToOne: false;
            referencedRelation: "problems";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "attempts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      beta_users: {
        Row: {
          active: boolean;
          created_at: string;
          display_name: string;
          email: string;
          id: string;
          role: Database["public"]["Enums"]["beta_role"];
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          display_name: string;
          email: string;
          id?: string;
          role?: Database["public"]["Enums"]["beta_role"];
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          display_name?: string;
          email?: string;
          id?: string;
          role?: Database["public"]["Enums"]["beta_role"];
          updated_at?: string;
        };
        Relationships: [];
      };
      coach_conversations: {
        Row: {
          created_at: string;
          id: string;
          project_id: string | null;
          session_id: string | null;
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          project_id?: string | null;
          session_id?: string | null;
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          project_id?: string | null;
          session_id?: string | null;
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "coach_conversations_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coach_conversations_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      coach_messages: {
        Row: {
          content: string;
          conversation_id: string;
          created_at: string;
          id: string;
          role: Database["public"]["Enums"]["coach_role"];
          user_id: string;
        };
        Insert: {
          content: string;
          conversation_id: string;
          created_at?: string;
          id?: string;
          role: Database["public"]["Enums"]["coach_role"];
          user_id?: string;
        };
        Update: {
          content?: string;
          conversation_id?: string;
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["coach_role"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "coach_messages_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "coach_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      favourite_gyms: {
        Row: {
          created_at: string;
          gym_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          gym_id: string;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          gym_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "favourite_gyms_gym_id_fkey";
            columns: ["gym_id"];
            isOneToOne: false;
            referencedRelation: "gyms";
            referencedColumns: ["id"];
          },
        ];
      };
      gyms: {
        Row: {
          active: boolean;
          brand: Database["public"]["Enums"]["gym_brand"];
          city: string | null;
          country: string | null;
          created_at: string;
          created_by: string | null;
          external_id: string | null;
          external_provider: string | null;
          grading_system: Database["public"]["Enums"]["grade_system"];
          id: string;
          latitude: number | null;
          longitude: number | null;
          name: string;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          brand: Database["public"]["Enums"]["gym_brand"];
          city?: string | null;
          country?: string | null;
          created_at?: string;
          created_by?: string | null;
          external_id?: string | null;
          external_provider?: string | null;
          grading_system: Database["public"]["Enums"]["grade_system"];
          id?: string;
          latitude?: number | null;
          longitude?: number | null;
          name: string;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          brand?: Database["public"]["Enums"]["gym_brand"];
          city?: string | null;
          country?: string | null;
          created_at?: string;
          created_by?: string | null;
          external_id?: string | null;
          external_provider?: string | null;
          grading_system?: Database["public"]["Enums"]["grade_system"];
          id?: string;
          latitude?: number | null;
          longitude?: number | null;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      media: {
        Row: {
          attempt_id: string | null;
          created_at: string;
          duration_seconds: number | null;
          height: number | null;
          id: string;
          media_type: Database["public"]["Enums"]["media_type"];
          mime_type: string;
          problem_id: string | null;
          session_id: string | null;
          size_bytes: number;
          storage_path: string;
          thumbnail_path: string | null;
          user_id: string;
          width: number | null;
        };
        Insert: {
          attempt_id?: string | null;
          created_at?: string;
          duration_seconds?: number | null;
          height?: number | null;
          id?: string;
          media_type: Database["public"]["Enums"]["media_type"];
          mime_type: string;
          problem_id?: string | null;
          session_id?: string | null;
          size_bytes: number;
          storage_path: string;
          thumbnail_path?: string | null;
          user_id?: string;
          width?: number | null;
        };
        Update: {
          attempt_id?: string | null;
          created_at?: string;
          duration_seconds?: number | null;
          height?: number | null;
          id?: string;
          media_type?: Database["public"]["Enums"]["media_type"];
          mime_type?: string;
          problem_id?: string | null;
          session_id?: string | null;
          size_bytes?: number;
          storage_path?: string;
          thumbnail_path?: string | null;
          user_id?: string;
          width?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "media_attempt_id_fkey";
            columns: ["attempt_id"];
            isOneToOne: false;
            referencedRelation: "attempts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "media_problem_id_fkey";
            columns: ["problem_id"];
            isOneToOne: false;
            referencedRelation: "problems";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "media_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      outdoor_areas: {
        Row: {
          cluster_name: string | null;
          description_en: string | null;
          description_fr: string | null;
          gym_id: string;
          id: number;
          name: string;
          name_searchable: string;
          north_east_lat: number | null;
          north_east_lon: number | null;
          priority: number;
          problems_count: number;
          south_west_lat: number | null;
          south_west_lon: number | null;
          tags: string[];
          updated_at: string;
          warning_en: string | null;
          warning_fr: string | null;
        };
        Insert: {
          cluster_name?: string | null;
          description_en?: string | null;
          description_fr?: string | null;
          gym_id: string;
          id: number;
          name: string;
          name_searchable?: string;
          north_east_lat?: number | null;
          north_east_lon?: number | null;
          priority?: number;
          problems_count?: number;
          south_west_lat?: number | null;
          south_west_lon?: number | null;
          tags?: string[];
          updated_at?: string;
          warning_en?: string | null;
          warning_fr?: string | null;
        };
        Update: {
          cluster_name?: string | null;
          description_en?: string | null;
          description_fr?: string | null;
          gym_id?: string;
          id?: number;
          name?: string;
          name_searchable?: string;
          north_east_lat?: number | null;
          north_east_lon?: number | null;
          priority?: number;
          problems_count?: number;
          south_west_lat?: number | null;
          south_west_lon?: number | null;
          tags?: string[];
          updated_at?: string;
          warning_en?: string | null;
          warning_fr?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "outdoor_areas_gym_id_fkey";
            columns: ["gym_id"];
            isOneToOne: true;
            referencedRelation: "gyms";
            referencedColumns: ["id"];
          },
        ];
      };
      outdoor_circuits: {
        Row: {
          average_grade: string | null;
          beginner_friendly: boolean;
          color: string;
          dangerous: boolean;
          id: number;
          updated_at: string;
        };
        Insert: {
          average_grade?: string | null;
          beginner_friendly?: boolean;
          color: string;
          dangerous?: boolean;
          id: number;
          updated_at?: string;
        };
        Update: {
          average_grade?: string | null;
          beginner_friendly?: boolean;
          color?: string;
          dangerous?: boolean;
          id?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      outdoor_data_imports: {
        Row: {
          areas: number;
          circuits: number;
          id: string;
          imported_at: string;
          problems: number;
          skipped: number;
          source: string;
          source_date: string | null;
          source_version: string | null;
        };
        Insert: {
          areas: number;
          circuits: number;
          id?: string;
          imported_at?: string;
          problems: number;
          skipped?: number;
          source: string;
          source_date?: string | null;
          source_version?: string | null;
        };
        Update: {
          areas?: number;
          circuits?: number;
          id?: string;
          imported_at?: string;
          problems?: number;
          skipped?: number;
          source?: string;
          source_date?: string | null;
          source_version?: string | null;
        };
        Relationships: [];
      };
      outdoor_problems: {
        Row: {
          area_id: number;
          bleau_info_id: string | null;
          circuit_color: string | null;
          circuit_id: number | null;
          circuit_number: string | null;
          featured: boolean;
          grade: string;
          id: number;
          latitude: number;
          longitude: number;
          name: string;
          name_en: string | null;
          name_searchable: string;
          parent_id: number | null;
          popularity: number | null;
          sit_start: boolean;
          steepness: string;
          updated_at: string;
          wall_angle: Database["public"]["Enums"]["wall_angle"];
        };
        Insert: {
          area_id: number;
          bleau_info_id?: string | null;
          circuit_color?: string | null;
          circuit_id?: number | null;
          circuit_number?: string | null;
          featured?: boolean;
          grade: string;
          id: number;
          latitude: number;
          longitude: number;
          name: string;
          name_en?: string | null;
          name_searchable?: string;
          parent_id?: number | null;
          popularity?: number | null;
          sit_start?: boolean;
          steepness: string;
          updated_at?: string;
          wall_angle?: Database["public"]["Enums"]["wall_angle"];
        };
        Update: {
          area_id?: number;
          bleau_info_id?: string | null;
          circuit_color?: string | null;
          circuit_id?: number | null;
          circuit_number?: string | null;
          featured?: boolean;
          grade?: string;
          id?: number;
          latitude?: number;
          longitude?: number;
          name?: string;
          name_en?: string | null;
          name_searchable?: string;
          parent_id?: number | null;
          popularity?: number | null;
          sit_start?: boolean;
          steepness?: string;
          updated_at?: string;
          wall_angle?: Database["public"]["Enums"]["wall_angle"];
        };
        Relationships: [
          {
            foreignKeyName: "outdoor_problems_area_id_fkey";
            columns: ["area_id"];
            isOneToOne: false;
            referencedRelation: "outdoor_areas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "outdoor_problems_circuit_id_fkey";
            columns: ["circuit_id"];
            isOneToOne: false;
            referencedRelation: "outdoor_circuits";
            referencedColumns: ["id"];
          },
        ];
      };
      problem_tags: {
        Row: {
          problem_id: string;
          tag_id: string;
        };
        Insert: {
          problem_id: string;
          tag_id: string;
        };
        Update: {
          problem_id?: string;
          tag_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "problem_tags_problem_id_fkey";
            columns: ["problem_id"];
            isOneToOne: false;
            referencedRelation: "problems";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "problem_tags_tag_id_fkey";
            columns: ["tag_id"];
            isOneToOne: false;
            referencedRelation: "tags";
            referencedColumns: ["id"];
          },
        ];
      };
      problems: {
        Row: {
          created_at: string;
          created_by: string;
          external_problem_id: string | null;
          gym_id: string;
          id: string;
          name: string | null;
          native_grade: string;
          native_grade_system: Database["public"]["Enums"]["grade_system"];
          normalization_confidence: number | null;
          normalization_source: Database["public"]["Enums"]["normalization_source"] | null;
          normalized_grade: string | null;
          normalized_grade_system: Database["public"]["Enums"]["grade_system"] | null;
          notes: string | null;
          opened_at: string | null;
          outdoor_problem_id: number | null;
          photo_url: string | null;
          retired_at: string | null;
          setter: string | null;
          updated_at: string;
          wall_angle: Database["public"]["Enums"]["wall_angle"];
          wall_zone: string | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string;
          external_problem_id?: string | null;
          gym_id: string;
          id?: string;
          name?: string | null;
          native_grade: string;
          native_grade_system: Database["public"]["Enums"]["grade_system"];
          normalization_confidence?: number | null;
          normalization_source?: Database["public"]["Enums"]["normalization_source"] | null;
          normalized_grade?: string | null;
          normalized_grade_system?: Database["public"]["Enums"]["grade_system"] | null;
          notes?: string | null;
          opened_at?: string | null;
          outdoor_problem_id?: number | null;
          photo_url?: string | null;
          retired_at?: string | null;
          setter?: string | null;
          updated_at?: string;
          wall_angle?: Database["public"]["Enums"]["wall_angle"];
          wall_zone?: string | null;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          external_problem_id?: string | null;
          gym_id?: string;
          id?: string;
          name?: string | null;
          native_grade?: string;
          native_grade_system?: Database["public"]["Enums"]["grade_system"];
          normalization_confidence?: number | null;
          normalization_source?: Database["public"]["Enums"]["normalization_source"] | null;
          normalized_grade?: string | null;
          normalized_grade_system?: Database["public"]["Enums"]["grade_system"] | null;
          notes?: string | null;
          opened_at?: string | null;
          outdoor_problem_id?: number | null;
          photo_url?: string | null;
          retired_at?: string | null;
          setter?: string | null;
          updated_at?: string;
          wall_angle?: Database["public"]["Enums"]["wall_angle"];
          wall_zone?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "problems_gym_id_fkey";
            columns: ["gym_id"];
            isOneToOne: false;
            referencedRelation: "gyms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "problems_outdoor_problem_id_fkey";
            columns: ["outdoor_problem_id"];
            isOneToOne: false;
            referencedRelation: "outdoor_problems";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          bio: string | null;
          climbing_since: string | null;
          created_at: string;
          display_name: string;
          height_cm: number | null;
          id: string;
          onboarding_completed_at: string | null;
          preferred_discipline: Database["public"]["Enums"]["discipline"];
          preferred_language: string;
          self_reported_level: string | null;
          self_reported_level_system: Database["public"]["Enums"]["grade_system"] | null;
          target_grade: string;
          target_grade_system: Database["public"]["Enums"]["grade_system"];
          updated_at: string;
          weight_kg: number | null;
        };
        Insert: {
          avatar_url?: string | null;
          bio?: string | null;
          climbing_since?: string | null;
          created_at?: string;
          display_name?: string;
          height_cm?: number | null;
          id: string;
          onboarding_completed_at?: string | null;
          preferred_discipline?: Database["public"]["Enums"]["discipline"];
          preferred_language?: string;
          self_reported_level?: string | null;
          self_reported_level_system?: Database["public"]["Enums"]["grade_system"] | null;
          target_grade?: string;
          target_grade_system?: Database["public"]["Enums"]["grade_system"];
          updated_at?: string;
          weight_kg?: number | null;
        };
        Update: {
          avatar_url?: string | null;
          bio?: string | null;
          climbing_since?: string | null;
          created_at?: string;
          display_name?: string;
          height_cm?: number | null;
          id?: string;
          onboarding_completed_at?: string | null;
          preferred_discipline?: Database["public"]["Enums"]["discipline"];
          preferred_language?: string;
          self_reported_level?: string | null;
          self_reported_level_system?: Database["public"]["Enums"]["grade_system"] | null;
          target_grade?: string;
          target_grade_system?: Database["public"]["Enums"]["grade_system"];
          updated_at?: string;
          weight_kg?: number | null;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          completed_at: string | null;
          created_at: string;
          id: string;
          notes: string | null;
          problem_id: string;
          started_at: string;
          status: Database["public"]["Enums"]["project_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          completed_at?: string | null;
          created_at?: string;
          id?: string;
          notes?: string | null;
          problem_id: string;
          started_at?: string;
          status?: Database["public"]["Enums"]["project_status"];
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          completed_at?: string | null;
          created_at?: string;
          id?: string;
          notes?: string | null;
          problem_id?: string;
          started_at?: string;
          status?: Database["public"]["Enums"]["project_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_problem_id_fkey";
            columns: ["problem_id"];
            isOneToOne: false;
            referencedRelation: "problems";
            referencedColumns: ["id"];
          },
        ];
      };
      sessions: {
        Row: {
          created_at: string;
          duration_minutes: number | null;
          ended_at: string | null;
          fatigue: number | null;
          gym_id: string;
          id: string;
          motivation: number | null;
          notes: string | null;
          perceived_energy_after: number | null;
          perceived_energy_before: number | null;
          session_type: Database["public"]["Enums"]["session_type"];
          source: Database["public"]["Enums"]["session_source"];
          started_at: string;
          updated_at: string;
          user_id: string;
          wearable_activity_id: string | null;
        };
        Insert: {
          created_at?: string;
          duration_minutes?: number | null;
          ended_at?: string | null;
          fatigue?: number | null;
          gym_id: string;
          id?: string;
          motivation?: number | null;
          notes?: string | null;
          perceived_energy_after?: number | null;
          perceived_energy_before?: number | null;
          session_type?: Database["public"]["Enums"]["session_type"];
          source?: Database["public"]["Enums"]["session_source"];
          started_at?: string;
          updated_at?: string;
          user_id?: string;
          wearable_activity_id?: string | null;
        };
        Update: {
          created_at?: string;
          duration_minutes?: number | null;
          ended_at?: string | null;
          fatigue?: number | null;
          gym_id?: string;
          id?: string;
          motivation?: number | null;
          notes?: string | null;
          perceived_energy_after?: number | null;
          perceived_energy_before?: number | null;
          session_type?: Database["public"]["Enums"]["session_type"];
          source?: Database["public"]["Enums"]["session_source"];
          started_at?: string;
          updated_at?: string;
          user_id?: string;
          wearable_activity_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "sessions_gym_id_fkey";
            columns: ["gym_id"];
            isOneToOne: false;
            referencedRelation: "gyms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_wearable_activity_fk";
            columns: ["wearable_activity_id"];
            isOneToOne: false;
            referencedRelation: "wearable_activities";
            referencedColumns: ["id"];
          },
        ];
      };
      tags: {
        Row: {
          created_at: string;
          id: string;
          slug: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          slug: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          slug?: string;
        };
        Relationships: [];
      };
      wearable_activities: {
        Row: {
          activity_type: string;
          avg_heart_rate: number | null;
          calories: number | null;
          created_at: string;
          dedup_key: string;
          device_manufacturer: string | null;
          device_name: string | null;
          duration_seconds: number;
          id: string;
          max_heart_rate: number | null;
          provider: Database["public"]["Enums"]["wearable_provider"];
          provider_activity_id: string;
          raw_file_reference: string | null;
          raw_metadata: Json | null;
          recovery_metrics: Json | null;
          session_id: string | null;
          started_at: string;
          training_load: number | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          activity_type?: string;
          avg_heart_rate?: number | null;
          calories?: number | null;
          created_at?: string;
          dedup_key: string;
          device_manufacturer?: string | null;
          device_name?: string | null;
          duration_seconds: number;
          id?: string;
          max_heart_rate?: number | null;
          provider: Database["public"]["Enums"]["wearable_provider"];
          provider_activity_id: string;
          raw_file_reference?: string | null;
          raw_metadata?: Json | null;
          recovery_metrics?: Json | null;
          session_id?: string | null;
          started_at: string;
          training_load?: number | null;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          activity_type?: string;
          avg_heart_rate?: number | null;
          calories?: number | null;
          created_at?: string;
          dedup_key?: string;
          device_manufacturer?: string | null;
          device_name?: string | null;
          duration_seconds?: number;
          id?: string;
          max_heart_rate?: number | null;
          provider?: Database["public"]["Enums"]["wearable_provider"];
          provider_activity_id?: string;
          raw_file_reference?: string | null;
          raw_metadata?: Json | null;
          recovery_metrics?: Json | null;
          session_id?: string | null;
          started_at?: string;
          training_load?: number | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wearable_activities_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      wearable_activity_samples: {
        Row: {
          activity_id: string;
          created_at: string;
          heart_rate: NonNullable<Json>;
          user_id: string;
        };
        Insert: {
          activity_id: string;
          created_at?: string;
          heart_rate?: NonNullable<Json>;
          user_id?: string;
        };
        Update: {
          activity_id?: string;
          created_at?: string;
          heart_rate?: NonNullable<Json>;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wearable_activity_samples_activity_id_fkey";
            columns: ["activity_id"];
            isOneToOne: true;
            referencedRelation: "wearable_activities";
            referencedColumns: ["id"];
          },
        ];
      };
      wearable_connections: {
        Row: {
          access_token_encrypted: string | null;
          created_at: string;
          expires_at: string | null;
          id: string;
          last_error: string | null;
          last_sync_at: string | null;
          provider: Database["public"]["Enums"]["wearable_provider"];
          provider_user_id: string | null;
          refresh_token_encrypted: string | null;
          scopes: string[] | null;
          status: Database["public"]["Enums"]["connection_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          access_token_encrypted?: string | null;
          created_at?: string;
          expires_at?: string | null;
          id?: string;
          last_error?: string | null;
          last_sync_at?: string | null;
          provider: Database["public"]["Enums"]["wearable_provider"];
          provider_user_id?: string | null;
          refresh_token_encrypted?: string | null;
          scopes?: string[] | null;
          status: Database["public"]["Enums"]["connection_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          access_token_encrypted?: string | null;
          created_at?: string;
          expires_at?: string | null;
          id?: string;
          last_error?: string | null;
          last_sync_at?: string | null;
          provider?: Database["public"]["Enums"]["wearable_provider"];
          provider_user_id?: string | null;
          refresh_token_encrypted?: string | null;
          scopes?: string[] | null;
          status?: Database["public"]["Enums"]["connection_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      admin_beta_overview: {
        Args: Record<PropertyKey, never>;
        Returns: {
          active: boolean;
          coach_requests_30d: number;
          display_name: string;
          email: string;
          has_account: boolean;
          role: Database["public"]["Enums"]["beta_role"];
        }[];
      };
      current_email: { Args: Record<PropertyKey, never>; Returns: string };
      font_grades: { Args: Record<PropertyKey, never>; Returns: string[] };
      is_active_beta_user: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_valid_native_grade: {
        Args: { p_grade: string; p_system: Database["public"]["Enums"]["grade_system"] };
        Returns: boolean;
      };
      link_wearable_activity: { Args: { p_activity_id: string; p_session_id: string }; Returns: undefined };
      log_attempt: {
        Args: { p_problem_id: string; p_result: Database["public"]["Enums"]["attempt_result"]; p_session_id: string };
        Returns: {
          attempt_number: number;
          created_at: string;
          id: string;
          notes: string | null;
          perceived_difficulty: number | null;
          problem_id: string;
          result: Database["public"]["Enums"]["attempt_result"];
          session_id: string;
          started_at: string | null;
          user_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "attempts";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      unlink_wearable_activity: { Args: { p_activity_id: string }; Returns: undefined };
    };
    Enums: {
      attempt_result: "ATTEMPT" | "TOP" | "FLASH";
      beta_role: "admin" | "beta_tester";
      coach_role: "user" | "assistant";
      connection_status: "CONNECTED" | "DISCONNECTED" | "ERROR";
      discipline: "bouldering" | "sport";
      grade_system: "ARKOSE_COLOR" | "CLIMBING_DISTRICT_COLOR" | "FONT" | "CUSTOM_COLOR" | "UNKNOWN";
      gym_brand: "ARKOSE" | "CLIMBING_DISTRICT" | "BLOCKOUT" | "INDEPENDENT" | "OUTDOOR" | "OTHER";
      media_type: "PROBLEM_PHOTO" | "ATTEMPT_VIDEO" | "SEND_VIDEO";
      normalization_source: "FONT_NATIVE" | "USER_ESTIMATE" | "GYM_PUBLISHED";
      project_status: "ACTIVE" | "SENT" | "ABANDONED" | "RETIRED";
      session_source: "MANUAL" | "ARKOSE" | "CLIMBING_DISTRICT" | "COROS" | "SUUNTO" | "GARMIN" | "STRAVA" | "IMPORT";
      session_type: "BOULDERING" | "TRAINING" | "PROJECTING" | "TECHNIQUE" | "OTHER";
      wall_angle: "SLAB" | "VERTICAL" | "SLIGHT_OVERHANG" | "OVERHANG" | "STEEP" | "ROOF" | "UNKNOWN";
      wearable_provider: "COROS" | "SUUNTO" | "GARMIN" | "STRAVA" | "FIT_IMPORT";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      attempt_result: ["ATTEMPT", "TOP", "FLASH"],
      beta_role: ["admin", "beta_tester"],
      coach_role: ["user", "assistant"],
      connection_status: ["CONNECTED", "DISCONNECTED", "ERROR"],
      discipline: ["bouldering", "sport"],
      grade_system: ["ARKOSE_COLOR", "CLIMBING_DISTRICT_COLOR", "FONT", "CUSTOM_COLOR", "UNKNOWN"],
      gym_brand: ["ARKOSE", "CLIMBING_DISTRICT", "BLOCKOUT", "INDEPENDENT", "OUTDOOR", "OTHER"],
      media_type: ["PROBLEM_PHOTO", "ATTEMPT_VIDEO", "SEND_VIDEO"],
      normalization_source: ["FONT_NATIVE", "USER_ESTIMATE", "GYM_PUBLISHED"],
      project_status: ["ACTIVE", "SENT", "ABANDONED", "RETIRED"],
      session_source: ["MANUAL", "ARKOSE", "CLIMBING_DISTRICT", "COROS", "SUUNTO", "GARMIN", "STRAVA", "IMPORT"],
      session_type: ["BOULDERING", "TRAINING", "PROJECTING", "TECHNIQUE", "OTHER"],
      wall_angle: ["SLAB", "VERTICAL", "SLIGHT_OVERHANG", "OVERHANG", "STEEP", "ROOF", "UNKNOWN"],
      wearable_provider: ["COROS", "SUUNTO", "GARMIN", "STRAVA", "FIT_IMPORT"],
    },
  },
} as const;
